  PREFIX schema: <http://schema.org/>
  DELETE {
      ?event schema:startDate ?old_date .
  }
  INSERT {
      ?event schema:startDate ?fixed_date .
  }
  WHERE {
    ?event a schema:Event ;
    ?p ?old_date.
    FILTER (datatype(?old_date) = schema:Date)
    BIND(STRDT(CONCAT(SUBSTR(str(?old_date), 1, (STRLEN(str(?old_date)) - 2)), ":", SUBSTR(str(?old_date), (STRLEN(str(?old_date)) - 1), 2)), schema:Date) as ?fixed_date)
  }