name: Run Main Script

on:
  workflow_dispatch:
    inputs:
      page_url:
        description: 'Page URL to loop pages'
        required: true
      base_url:
        description: 'Base URL'
        required: true
      entity_identifier:
        description: 'Entity html tag'
        required: true
      file_name:
        description: 'File Name'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Ruby
      uses: actions/setup-ruby@v1
      with:
        ruby-version: '3.1'
        bundler-cache: true
    - run: bundle exec rake

    - name: Install Dependencies
      run: |
        gem install nokogiri linkeddata

    - name: Run Main Script
      run: ruby main.rb ${{ github.event.inputs.page_url }} ${{ github.event.inputs.base_url }} ${{ github.event.inputs.entity_identifier }} ${{ github.event.inputs.file_name }}

    - name: Commit and Push Changes
      run: |
        git config --local user.email "actions@github.com"
        git config --local user.name "GitHub Actions"
        git add ${{ github.event.inputs.file_name }}
        git commit -m "Add data generated by the script"
        git push
