name: Fetch Scenesfrancophones Events

on:
  workflow_dispatch:
  schedule:
    - cron: "0 5 * * 1"  # Run at 1:00 AM ET every Monday

jobs:
  fetch-and-commit-data:
    runs-on: ubuntu-latest
    outputs:
      changes: ${{ steps.check-changes.outputs.HAS_CHANGES }}
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        bundler-cache: true
    - name: Run Main Script
      run: bundle exec ruby main.rb https://scenesfrancophones.ca/spectacles?page= https://scenesfrancophones.ca div.title output/events.jsonld

    - name: Check for file changes
      id: check-changes
      run: |
        if [ -n "$(git diff --cached outputs/events.jsonld)" ]; then
          echo "HAS_CHANGES=true" >> $GITHUB_OUTPUT
        fi
      shell: bash

    - name: Commit and Push Changes
      if: steps.check-changes.outputs.HAS_CHANGES == 'true'
      run: |
        git config --local user.email "actions@github.com"
        git config --local user.name "GitHub Actions"
        git pull
        git add "output/events.jsonld"
        git commit -m "Add data generated by the script"
        git push

  artsdata-push:
    runs-on: ubuntu-latest
    needs: fetch-and-commit-data
    if: needs.fetch-and-commit-data.outputs.changes == 'true'
    steps:
      - name: Action setup
        uses: culturecreates/artsdata-pipeline-action@v1.1.0
        with:
          artifact: scenesfrancophones-events
          publisher: "${{ secrets.PUBLISHER_URI_GREGORY }}"
          downloadUrl: "https://raw.githubusercontent.com/culturecreates/artsdata-planet-scenesfrancophones/main/output/events.jsonld"
